import { LegalPageLayout } from "@/components/legal/LegalPageLayout";

export const metadata = { title: "Disclaimer — DocuForge AI" };

export default function DisclaimerPage() {
  return (
    <LegalPageLayout title="Disclaimer" lastUpdated="June 16, 2025">
      <section>
        <h2 className="text-xl font-semibold text-white">1. AI-Generated Content</h2>
        <p>All videos, scripts, narration, and images produced by DocuForge AI are generated by artificial intelligence. While we use live web research to improve factual accuracy, <strong>AI-generated content may contain errors, inaccuracies, or outdated information</strong>. You are responsible for reviewing and verifying all content before publishing.</p>
      </section>
      <section>
        <h2 className="text-xl font-semibold text-white">2. No Professional Advice</h2>
        <p>Content generated on our platform does not constitute legal, medical, financial, or professional advice. Do not rely on AI-generated documentaries or shorts for critical decisions.</p>
      </section>
      <section>
        <h2 className="text-xl font-semibold text-white">3. Third-Party Data</h2>
        <p>Our platform scrapes publicly available data from third-party sources (Wikipedia, news APIs, search engines, etc.). We do not guarantee the accuracy, completeness, or legality of scraped data. Respect copyright and licensing of source materials.</p>
      </section>
      <section>
        <h2 className="text-xl font-semibold text-white">4. Service Availability</h2>
        <p>We strive for 99.9% uptime but do not guarantee uninterrupted access. Scheduled maintenance, API outages from third-party providers (ElevenLabs, NVIDIA, etc.), or force majeure events may affect service availability.</p>
      </section>
      <section>
        <h2 className="text-xl font-semibold text-white">5. Limitation of Liability</h2>
        <p>To the maximum extent permitted by law, DocuForge AI and its affiliates shall not be liable for any damages arising from use of generated content, including but not limited to lost revenue, reputational harm, or copyright claims resulting from published videos.</p>
      </section>
      <section>
        <h2 className="text-xl font-semibold text-white">6. User Responsibility</h2>
        <p>You are solely responsible for ensuring your published content complies with YouTube, TikTok, Instagram, and other platform community guidelines, as well as applicable local laws.</p>
      </section>
    </LegalPageLayout>
  );
}
