/** Mock admin data for preview mode */
import type { AdminUsersData, ScraperStatus, SettingItem } from "@/lib/admin/types";

const SCRAPER_TOGGLES: SettingItem[] = [
  { key: "scraper_tavily_enabled", value: "true", category: "scraping", label: "Enable Tavily", is_secret: false, value_masked: null },
  { key: "scraper_jina_enabled", value: "true", category: "scraping", label: "Enable Jina AI", is_secret: false, value_masked: null },
  { key: "scraper_serper_enabled", value: "true", category: "scraping", label: "Enable Serper", is_secret: false, value_masked: null },
  { key: "scraper_firecrawl_enabled", value: "true", category: "scraping", label: "Enable Firecrawl", is_secret: false, value_masked: null },
  { key: "scraper_exa_enabled", value: "true", category: "scraping", label: "Enable Exa", is_secret: false, value_masked: null },
  { key: "scraper_brave_enabled", value: "true", category: "scraping", label: "Enable Brave Search", is_secret: false, value_masked: null },
  { key: "scraper_newsapi_enabled", value: "true", category: "scraping", label: "Enable NewsAPI", is_secret: false, value_masked: null },
  { key: "scraper_google_cse_enabled", value: "false", category: "scraping", label: "Enable Google CSE", is_secret: false, value_masked: null },
  { key: "scraper_wikipedia_enabled", value: "true", category: "scraping", label: "Enable Wikipedia", is_secret: false, value_masked: null },
  { key: "scraper_internet_archive_enabled", value: "true", category: "scraping", label: "Enable Internet Archive", is_secret: false, value_masked: null },
];

export const DEMO_ADMIN_SETTINGS: SettingItem[] = [
  { key: "tavily_api_key", value: "", category: "scraping", label: "Tavily API Key", is_secret: true, value_masked: null },
  { key: "jina_api_key", value: "", category: "scraping", label: "Jina AI API Key", is_secret: true, value_masked: null },
  { key: "serper_api_key", value: "", category: "scraping", label: "Serper (Google Search) API Key", is_secret: true, value_masked: null },
  { key: "firecrawl_api_key", value: "", category: "scraping", label: "Firecrawl API Key", is_secret: true, value_masked: null },
  { key: "exa_api_key", value: "", category: "scraping", label: "Exa AI Search API Key", is_secret: true, value_masked: null },
  { key: "brave_search_api_key", value: "", category: "scraping", label: "Brave Search API Key", is_secret: true, value_masked: null },
  { key: "newsapi_key", value: "", category: "scraping", label: "NewsAPI Key", is_secret: true, value_masked: null },
  { key: "google_cse_api_key", value: "", category: "scraping", label: "Google Custom Search API Key", is_secret: true, value_masked: null },
  { key: "google_cse_cx", value: "", category: "scraping", label: "Google CSE Engine ID (cx)", is_secret: false, value_masked: null },
  { key: "claude_api_key", value: "", category: "llm", label: "Anthropic Claude API Key", is_secret: true, value_masked: null },
  { key: "claude_model", value: "claude-sonnet-4-20250514", category: "llm", label: "Claude Model ID", is_secret: false, value_masked: null },
  { key: "research_llm", value: "claude", category: "llm", label: "Research LLM", is_secret: false, value_masked: null },
  { key: "script_llm", value: "claude_then_llama", category: "llm", label: "Script LLM", is_secret: false, value_masked: null },
  { key: "nvidia_nim_api_key", value: "", category: "media", label: "NVIDIA NIM API Key", is_secret: true, value_masked: null },
  { key: "elevenlabs_api_key", value: "", category: "media", label: "ElevenLabs API Key", is_secret: true, value_masked: null },
  { key: "elevenlabs_voice_id", value: "21m00Tcm4TlvDq8ikWAM", category: "media", label: "ElevenLabs Voice ID", is_secret: false, value_masked: null },
  { key: "pexels_api_key", value: "", category: "media", label: "Pexels API Key", is_secret: true, value_masked: null },
  { key: "pixabay_api_key", value: "", category: "media", label: "Pixabay API Key", is_secret: true, value_masked: null },
  { key: "mapbox_access_token", value: "", category: "media", label: "Mapbox Access Token", is_secret: true, value_masked: null },
  { key: "stripe_secret_key", value: "", category: "billing", label: "Stripe Secret Key", is_secret: true, value_masked: null },
  { key: "stripe_webhook_secret", value: "", category: "billing", label: "Stripe Webhook Secret", is_secret: true, value_masked: null },
  { key: "stripe_pro_price_id", value: "", category: "billing", label: "Stripe Pro Price ID", is_secret: false, value_masked: null },
  ...SCRAPER_TOGGLES,
];

export const DEMO_SCRAPER_STATUS: ScraperStatus[] = [
  { id: "tavily", label: "Tavily", enabled: true, configured: false, ready: false },
  { id: "jina", label: "Jina AI", enabled: true, configured: false, ready: false },
  { id: "serper", label: "Serper", enabled: true, configured: false, ready: false },
  { id: "firecrawl", label: "Firecrawl", enabled: true, configured: false, ready: false },
  { id: "exa", label: "Exa", enabled: true, configured: false, ready: false },
  { id: "brave", label: "Brave Search", enabled: true, configured: false, ready: false },
  { id: "newsapi", label: "NewsAPI", enabled: true, configured: false, ready: false },
  { id: "google_cse", label: "Google CSE", enabled: false, configured: false, ready: false },
  { id: "wikipedia", label: "Wikipedia", enabled: true, configured: true, ready: true },
  { id: "internet_archive", label: "Internet Archive", enabled: true, configured: true, ready: true },
];

export const DEMO_ADMIN_USERS: AdminUsersData = {
  summary: {
    total_users: 6,
    pro_users: 2,
    free_users: 4,
    total_videos_completed: 14,
    credits_per_video: 5,
  },
  users: [
    {
      user_id: "demo-1",
      email: "support@docuforge.pro",
      full_name: "Admin",
      plan_type: "pro",
      is_admin: true,
      signed_up_at: "2025-11-01T10:00:00Z",
      credits_remaining: 25,
      credits_used_estimate: 5,
      plan_credits_allocation: 30,
      documentary_jobs: 2,
      documentary_completed: 1,
      short_jobs: 3,
      shorts_completed: 2,
      videos_completed: 3,
      jobs_failed: 0,
      jobs_in_progress: 1,
      last_active_at: "2026-06-15T14:30:00Z",
      stripe_customer_id: "cus_demo_admin",
      billing_cycle_end: "2026-07-01T00:00:00Z",
    },
    {
      user_id: "demo-2",
      email: "sarah.chen@example.com",
      full_name: "Sarah Chen",
      plan_type: "pro",
      is_admin: false,
      signed_up_at: "2026-01-12T08:15:00Z",
      credits_remaining: 10,
      credits_used_estimate: 20,
      plan_credits_allocation: 30,
      documentary_jobs: 1,
      documentary_completed: 1,
      short_jobs: 5,
      shorts_completed: 3,
      videos_completed: 4,
      jobs_failed: 1,
      jobs_in_progress: 0,
      last_active_at: "2026-06-14T09:00:00Z",
      stripe_customer_id: "cus_demo_sarah",
      billing_cycle_end: "2026-07-12T00:00:00Z",
    },
    {
      user_id: "demo-3",
      email: "mike.j@example.com",
      full_name: "Mike Johnson",
      plan_type: "free",
      is_admin: false,
      signed_up_at: "2026-02-20T16:45:00Z",
      credits_remaining: 0,
      credits_used_estimate: 5,
      plan_credits_allocation: 5,
      documentary_jobs: 0,
      documentary_completed: 0,
      short_jobs: 1,
      shorts_completed: 1,
      videos_completed: 1,
      jobs_failed: 0,
      jobs_in_progress: 0,
      last_active_at: "2026-02-21T11:00:00Z",
    },
    {
      user_id: "demo-4",
      email: "priya@startup.io",
      full_name: "Priya Sharma",
      plan_type: "free",
      is_admin: false,
      signed_up_at: "2026-03-05T12:00:00Z",
      credits_remaining: 5,
      credits_used_estimate: 0,
      plan_credits_allocation: 5,
      documentary_jobs: 0,
      documentary_completed: 0,
      short_jobs: 0,
      shorts_completed: 0,
      videos_completed: 0,
      jobs_failed: 0,
      jobs_in_progress: 0,
      last_active_at: null,
    },
    {
      user_id: "demo-5",
      email: "alex.creator@gmail.com",
      full_name: "Alex Rivera",
      plan_type: "free",
      is_admin: false,
      signed_up_at: "2026-05-18T20:30:00Z",
      credits_remaining: 0,
      credits_used_estimate: 10,
      plan_credits_allocation: 5,
      documentary_jobs: 1,
      documentary_completed: 1,
      short_jobs: 1,
      shorts_completed: 1,
      videos_completed: 2,
      jobs_failed: 1,
      jobs_in_progress: 0,
      last_active_at: "2026-05-19T18:00:00Z",
    },
    {
      user_id: "demo-6",
      email: "emma@agency.co",
      full_name: "Emma Wilson",
      plan_type: "free",
      is_admin: false,
      signed_up_at: "2026-06-10T07:00:00Z",
      credits_remaining: 5,
      credits_used_estimate: 0,
      plan_credits_allocation: 5,
      documentary_jobs: 0,
      documentary_completed: 0,
      short_jobs: 0,
      shorts_completed: 0,
      videos_completed: 0,
      jobs_failed: 0,
      jobs_in_progress: 0,
      last_active_at: null,
    },
  ],
};
