name: Deploy Frontend to AWS S3

on:
  push:
    branches:
      - main
    paths:
      - 'frontend/**'
      - '.github/workflows/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install Dependencies & Build
      run: |
        cd frontend
        npm install
        npm run build
      env:
        NEXT_PUBLIC_API_URL: https://fxfken83p0.execute-api.us-east-1.amazonaws.com
        NEXT_PUBLIC_SITE_URL: https://docuforge.pro

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Deploy Frontend to S3
      run: |
        echo "Syncing static files..."
        # static export check karne ke liye hum frontend/out folder sync karenge
        aws s3 sync frontend/out s3://docuforge-serverless-frontendbucket-12t7hivg0fdb --delete

    - name: Invalidate CloudFront Cache
      run: |
        aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"
